### ISSUE TITLE
Tutorial Error: Failed to load external module @babel/register

### ISSUE THREAD

**Issue by AlexandroPerez** [addyosmani/critical-path-css-demo#12]
I get the following error when running the tutorial in Windows 10 using WSL (Ubuntu on Windows). I have followed the instructions and I keep getting this error.

```
$ gulp critical
[13:11:04] Failed to load external module @babel/register
[13:11:04] Requiring external module babel-register
[13:11:09] Using gulpfile /mnt/d/workspace/myapp/gulpfile.babel.js
[13:11:09] Starting 'lint'...
[13:11:09] Starting 'styles'...
[13:11:10] Starting 'scripts'...
[13:11:10] Starting 'images'...
[13:11:10] Starting 'fonts'...
[13:11:10] Starting 'extras'...
(node:383) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[13:11:10] Finished 'images' after 661 ms
[13:11:10] Finished 'fonts' after 152 ms
[13:11:11] Finished 'lint' after 1.79 s
[13:11:11] Finished 'styles' after 1.38 s
[13:11:11] Finished 'scripts' after 942 ms
[13:11:11] Starting 'html'...

events.js:183
      throw er; // Unhandled 'error' event
      ^
Error
    at new JS_Parse_Error (eval at <anonymous> (/mnt/d/workspace/myapp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (/mnt/d/workspace/myapp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1542:11)
    at croak (eval at <anonymous> (/mnt/d/workspace/myapp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2089:9)
    at token_error (eval at <anonymous> (/mnt/d/workspace/myapp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2097:9)
    at unexpected (eval at <anonymous> (/mnt/d/workspace/myapp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2103:9)
    at expr_atom (eval at <anonymous> (/mnt/d/workspace/myapp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2630:9)
    at maybe_unary (eval at <anonymous> (/mnt/d/workspace/myapp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2792:19)
    at expr_ops (eval at <anonymous> (/mnt/d/workspace/myapp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2827:24)
    at maybe_conditional (eval at <anonymous> (/mnt/d/workspace/myapp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2832:20)
    at maybe_assign (eval at <anonymous> (/mnt/d/workspace/myapp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2856:20)
    at expression (eval at <anonymous> (/mnt/d/workspace/myapp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2875:20)
    at simple_statement (eval at <anonymous> (/mnt/d/workspace/myapp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2314:55)
    at eval (eval at <anonymous> (/mnt/d/workspace/myapp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2178:20)
    at eval (eval at <anonymous> (/mnt/d/workspace/myapp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2136:24)
    at eval (eval at <anonymous> (/mnt/d/workspace/myapp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2904:23)
    at Object.parse (eval at <anonymous> (/mnt/d/workspace/myapp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2915:7)
    at /mnt/d/workspace/myapp/node_modules/uglify-js/tools/node.js:71:33
    at Array.forEach (<anonymous>)
    at Object.exports.minify (/mnt/d/workspace/myapp/node_modules/uglify-js/tools/node.js:66:15)
    at /mnt/d/workspace/myapp/node_modules/gulp-uglify/minifier.js:65:22
    at trycatch (/mnt/d/workspace/myapp/node_modules/gulp-uglify/minifier.js:15:12)
    at DestroyableTransform.minify [as _transform] (/mnt/d/workspace/myapp/node_modules/gulp-uglify/minifier.js:64:19)
```

**Comment by KaranSantra** [comment]
I am facing the same issue too.
