### ISSUE TITLE
primordials is not defined

### ISSUE THREAD

**Issue by ksunny764** [addyosmani/critical-path-css-demo#15]
D:\Projects\Criticle CSS Demo\myapp>gulp critical
[11:35:20] Requiring external module babel-core/register
fs.js:35
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:35:5
    at req_ (D:\Projects\Criticle CSS Demo\myapp\node_modules\natives\index.js:143:24)
    at Object.req [as require] (D:\Projects\Criticle CSS Demo\myapp\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (D:\Projects\Criticle CSS Demo\myapp\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Object.require.extensions.<computed> [as .js] (D:\Projects\Criticle CSS Demo\myapp\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)

**Comment by wingear** [comment]
Probably your current version of Node.js is not compatible. Try use different version.
